services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_USER
        sync: false
      - key: N8N_PASSWORD
        sync: false
      - key: WEBHOOK_URL
        sync: false
